# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pyvelociraptor/api.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18pyvelociraptor/api.proto\x12\x05proto\x1a\x1bgoogle/protobuf/empty.proto\"\'\n\nVQLRequest\x12\x0c\n\x04Name\x18\x02 \x01(\t\x12\x0b\n\x03VQL\x18\x01 \x01(\t\"$\n\x06VQLEnv\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\x9b\x01\n\x10VQLCollectorArgs\x12\x1a\n\x03\x65nv\x18\x03 \x03(\x0b\x32\r.proto.VQLEnv\x12 \n\x05Query\x18\x02 \x03(\x0b\x32\x11.proto.VQLRequest\x12\x0f\n\x07max_row\x18\x04 \x01(\x04\x12\x10\n\x08max_wait\x18\x06 \x01(\x04\x12\x16\n\x0eops_per_second\x18\x18 \x01(\x02\x12\x0e\n\x06org_id\x18# \x01(\t\"*\n\nVQLTypeMap\x12\x0e\n\x06\x63olumn\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\"\xc8\x01\n\x0bVQLResponse\x12\x10\n\x08Response\x18\x01 \x01(\t\x12\x0f\n\x07\x43olumns\x18\x02 \x03(\t\x12 \n\x05types\x18\x08 \x03(\x0b\x32\x11.proto.VQLTypeMap\x12\x10\n\x08query_id\x18\x05 \x01(\x04\x12\x0c\n\x04part\x18\x06 \x01(\x04\x12 \n\x05Query\x18\x03 \x01(\x0b\x32\x11.proto.VQLRequest\x12\x11\n\ttimestamp\x18\x04 \x01(\x04\x12\x12\n\ntotal_rows\x18\x07 \x01(\x04\x12\x0b\n\x03log\x18\t \x01(\t\"d\n\rVFSFileBuffer\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x0e\n\x06offset\x18\x03 \x01(\x04\x12\x0e\n\x06length\x18\x04 \x01(\r\x12\x0c\n\x04\x64\x61ta\x18\x05 \x01(\x0c\x12\x12\n\ncomponents\x18\x06 \x03(\t2\xb9\x01\n\x03\x41PI\x12\x38\n\x05Query\x12\x17.proto.VQLCollectorArgs\x1a\x12.proto.VQLResponse\"\x00\x30\x01\x12<\n\x0cVFSGetBuffer\x12\x14.proto.VFSFileBuffer\x1a\x14.proto.VFSFileBuffer\"\x00\x12:\n\nWriteEvent\x12\x12.proto.VQLResponse\x1a\x16.google.protobuf.Empty\"\x00\x62\x06proto3')



_VQLREQUEST = DESCRIPTOR.message_types_by_name['VQLRequest']
_VQLENV = DESCRIPTOR.message_types_by_name['VQLEnv']
_VQLCOLLECTORARGS = DESCRIPTOR.message_types_by_name['VQLCollectorArgs']
_VQLTYPEMAP = DESCRIPTOR.message_types_by_name['VQLTypeMap']
_VQLRESPONSE = DESCRIPTOR.message_types_by_name['VQLResponse']
_VFSFILEBUFFER = DESCRIPTOR.message_types_by_name['VFSFileBuffer']
VQLRequest = _reflection.GeneratedProtocolMessageType('VQLRequest', (_message.Message,), {
  'DESCRIPTOR' : _VQLREQUEST,
  '__module__' : 'pyvelociraptor.api_pb2'
  # @@protoc_insertion_point(class_scope:proto.VQLRequest)
  })
_sym_db.RegisterMessage(VQLRequest)

VQLEnv = _reflection.GeneratedProtocolMessageType('VQLEnv', (_message.Message,), {
  'DESCRIPTOR' : _VQLENV,
  '__module__' : 'pyvelociraptor.api_pb2'
  # @@protoc_insertion_point(class_scope:proto.VQLEnv)
  })
_sym_db.RegisterMessage(VQLEnv)

VQLCollectorArgs = _reflection.GeneratedProtocolMessageType('VQLCollectorArgs', (_message.Message,), {
  'DESCRIPTOR' : _VQLCOLLECTORARGS,
  '__module__' : 'pyvelociraptor.api_pb2'
  # @@protoc_insertion_point(class_scope:proto.VQLCollectorArgs)
  })
_sym_db.RegisterMessage(VQLCollectorArgs)

VQLTypeMap = _reflection.GeneratedProtocolMessageType('VQLTypeMap', (_message.Message,), {
  'DESCRIPTOR' : _VQLTYPEMAP,
  '__module__' : 'pyvelociraptor.api_pb2'
  # @@protoc_insertion_point(class_scope:proto.VQLTypeMap)
  })
_sym_db.RegisterMessage(VQLTypeMap)

VQLResponse = _reflection.GeneratedProtocolMessageType('VQLResponse', (_message.Message,), {
  'DESCRIPTOR' : _VQLRESPONSE,
  '__module__' : 'pyvelociraptor.api_pb2'
  # @@protoc_insertion_point(class_scope:proto.VQLResponse)
  })
_sym_db.RegisterMessage(VQLResponse)

VFSFileBuffer = _reflection.GeneratedProtocolMessageType('VFSFileBuffer', (_message.Message,), {
  'DESCRIPTOR' : _VFSFILEBUFFER,
  '__module__' : 'pyvelociraptor.api_pb2'
  # @@protoc_insertion_point(class_scope:proto.VFSFileBuffer)
  })
_sym_db.RegisterMessage(VFSFileBuffer)

_API = DESCRIPTOR.services_by_name['API']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VQLREQUEST._serialized_start=64
  _VQLREQUEST._serialized_end=103
  _VQLENV._serialized_start=105
  _VQLENV._serialized_end=141
  _VQLCOLLECTORARGS._serialized_start=144
  _VQLCOLLECTORARGS._serialized_end=299
  _VQLTYPEMAP._serialized_start=301
  _VQLTYPEMAP._serialized_end=343
  _VQLRESPONSE._serialized_start=346
  _VQLRESPONSE._serialized_end=546
  _VFSFILEBUFFER._serialized_start=548
  _VFSFILEBUFFER._serialized_end=648
  _API._serialized_start=651
  _API._serialized_end=836
# @@protoc_insertion_point(module_scope)
