# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from pyvelociraptor import api_pb2 as pyvelociraptor_dot_api__pb2


class APIStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Query = channel.unary_stream(
                '/proto.API/Query',
                request_serializer=pyvelociraptor_dot_api__pb2.VQLCollectorArgs.SerializeToString,
                response_deserializer=pyvelociraptor_dot_api__pb2.VQLResponse.FromString,
                )
        self.VFSGetBuffer = channel.unary_unary(
                '/proto.API/VFSGetBuffer',
                request_serializer=pyvelociraptor_dot_api__pb2.VFSFileBuffer.SerializeToString,
                response_deserializer=pyvelociraptor_dot_api__pb2.VFSFileBuffer.FromString,
                )
        self.WriteEvent = channel.unary_unary(
                '/proto.API/WriteEvent',
                request_serializer=pyvelociraptor_dot_api__pb2.VQLResponse.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class APIServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Query(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VFSGetBuffer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_APIServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Query': grpc.unary_stream_rpc_method_handler(
                    servicer.Query,
                    request_deserializer=pyvelociraptor_dot_api__pb2.VQLCollectorArgs.FromString,
                    response_serializer=pyvelociraptor_dot_api__pb2.VQLResponse.SerializeToString,
            ),
            'VFSGetBuffer': grpc.unary_unary_rpc_method_handler(
                    servicer.VFSGetBuffer,
                    request_deserializer=pyvelociraptor_dot_api__pb2.VFSFileBuffer.FromString,
                    response_serializer=pyvelociraptor_dot_api__pb2.VFSFileBuffer.SerializeToString,
            ),
            'WriteEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteEvent,
                    request_deserializer=pyvelociraptor_dot_api__pb2.VQLResponse.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.API', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class API(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Query(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/proto.API/Query',
            pyvelociraptor_dot_api__pb2.VQLCollectorArgs.SerializeToString,
            pyvelociraptor_dot_api__pb2.VQLResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def VFSGetBuffer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.API/VFSGetBuffer',
            pyvelociraptor_dot_api__pb2.VFSFileBuffer.SerializeToString,
            pyvelociraptor_dot_api__pb2.VFSFileBuffer.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def WriteEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.API/WriteEvent',
            pyvelociraptor_dot_api__pb2.VQLResponse.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
